
all:
  vars:
    ansible_user: root

  children:
    web:
      hosts:
        web-1:
          ansible_host: 178.105.44.112

    app:
      hosts:
        app-1:
          ansible_host: 178.105.44.169
