
all:
  vars:
    ansible_user: root

  children:
    web:
      hosts:
        web-1:
          ansible_host: 167.235.129.55

    app:
      hosts:
        app-1:
          ansible_host: 188.245.189.204
