
all:
  vars:
    ansible_user: root

  children:
    web:
      hosts:
        web-1:
          ansible_host: 157.90.227.59

    app:
      hosts:
        app-1:
          ansible_host: 157.90.226.73
