- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Allow SSH
  ufw:
    rule: allow
    port: 22

- name: Allow HTTP
  ufw:
    rule: allow
    port: 80

- name: Enable firewall
  ufw:
    state: enabled
    policy: allow

- name: Allow node_exporter port
  ufw:
    rule: allow
    port: 9100
    proto: tcp

- name: Allow Prometheus
  ufw:
    rule: allow
    port: '9090'

- name: Allow Grafana
  ufw:
    rule: allow
    port: '3000'
