- hosts: all
  become: true
  roles:
    - common
    - users
    - sudoers
    - ntp
    - firewall
    - fail2ban
    - motd
    - monitoring
    - node_exporter

- hosts: web
  become: true
  roles:
    - nginx

- hosts: app
  become: true
  roles:
    - prometheus
    - grafana
