- hosts: all
  become: true
  roles:
    - common
    - users
    - sudoers
    - ntp
    - firewall
    - fail2ban
    - motd
    - nginx
    - monitoring

- hosts: app
  become: true
  roles:
    - prometheus
    - grafana
