- name: Set MOTD
  copy:
    dest: /etc/motd
    content: |
      ******************************************
      DevOps Demo Environment
      Managed via Ansible
      Purpose: Web + App Servers
      ******************************************
