name: Full DevOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Ansible Syntax Check
        working-directory: ansible
        run: ansible-playbook playbooks/site.yml --syntax-check

  deploy:
    name: Deploy to Infrastructure
    runs-on: ubuntu-latest
    needs: validate
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Output
        working-directory: terraform
        run: terraform output -json > output.json

      - name: Install Python
        run: sudo apt-get install -y python3

      - name: Generate Ansible Inventory
        working-directory: terraform
        run: python3 generate_inventory.py

      - name: Install Ansible
        run: sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        working-directory: ansible
        run: ansible-playbook playbooks/site.yml
