name: Deploy Application (Ansible)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/hetzner_key
          chmod 600 ~/.ssh/hetzner_key

      - name: Run Ansible Playbook
        working-directory: ansible
        run: |
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook \
            -i inventories/production/inventory.yml \
            playbooks/site.yml \
            --private-key ~/.ssh/hetzner_key
