name: Deploy Application (Ansible)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Disable host key checking (simpler)
        run: |
          echo -e "[defaults]\nhost_key_checking = False" > ~/.ansible.cfg

      - name: Run Ansible Playbook
        working-directory: ansible
        run: |
          ansible-playbook -i inventories/production/inventory.yml playbooks/site.yml
